services:
  postgres-db:
    image: postgres:18-alpine
    container_name: user_management_db
    restart: always
    environment:
      # Matches your DATABASE_USERNAME
      POSTGRES_USER: root
      # Matches your DATABASE_PASSWORD
      POSTGRES_PASSWORD: root
      # Matches your DATABASE_URL (user_management)
      POSTGRES_DB: user_management
    ports:
      # Host 3307 maps to Container 5432
      - "3307:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: