spring:
  application:
    name: user-management
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/your_db_name
    username: postgres
    password: your_password

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.project.model
  configuration:
    map-underscore-to-camel-case: true
    # Ensures null values are handled correctly by Postgres types
    jdbc-type-for-null: 'NULL'